# Generated by Django 3.2.16 on 2025-12-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammartable',
            options={'ordering': ['-order'], 'verbose_name': 'Tabliča', 'verbose_name_plural': 'Tabličat'},
        ),
    ]
