import { library } from '@fortawesome/fontawesome-svg-core';
import { 
    faVolumeUp, 
    faBook, 
    faStar, 
    faSpinner, 
    faUsers,
    faArrowUp,
    faComment,     
    faLanguage,      
    faComments,     
    faBrain,        
    faBookOpenReader,    
    faTasks,        
    faFaceGrinStars,  
    faBookOpen,       
    faMusic,       
    faPencilAlt,   
    faSmile,       
    faHeadphones,   
    faQuestionCircle,
    faKey,               
    faExclamationTriangle,
    faArrowLeft,
    faArrowRight,
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

library.add(
    faVolumeUp, 
    faBook, 
    faStar, 
    faSpinner, 
    faUsers,
    faArrowUp,
    faComment,       
    faLanguage,     
    faComments,    
    faBrain,         
    faBookOpenReader, 
    faTasks,           
    faFaceGrinStars, 
    faBookOpen,      
    faMusic,        
    faPencilAlt,    
    faSmile,        
    faHeadphones,   
    faQuestionCircle,
    faKey,           
    faExclamationTriangle,
    faArrowLeft,
    faArrowRight,
);

export { FontAwesomeIcon };