# Generated by Django 3.2.16 on 2024-12-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Uroka',
                'verbose_name_plural': 'Urokat',
            },
        ),
    ]
