# Generated by Django 3.2.16 on 2025-01-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lessons', '0007_auto_20241231_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['number'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.RemoveField(
            model_name='lessonspeech',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lessonspeech',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='lessonspeech',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
