# Generated by Django 3.2.16 on 2025-01-25 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lessons', '0008_auto_20250125_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonspeech',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'lessons'), ('model', 'lesson')), models.Q(('app_label', 'lessons'), ('model', 'module')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
