# Generated by Django 3.2.16 on 2025-01-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_alter_lessonspeech_content_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["number"],
                "verbose_name": "Uroka",
                "verbose_name_plural": "Urokat",
            },
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="num",
            new_name="number",
        ),
    ]
