# Generated by Django 3.2.16 on 2025-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_auto_20250125_2247"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonspeech",
            name="text",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
