# Generated by Django 3.2.16 on 2025-02-02 14:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_module_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='HTML'),
        ),
    ]
