# Generated by Django 3.2.16 on 2025-02-03 23:25

import ckeditor.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_alter_module_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='HTML'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('FillBlank', 'FILL_BLANK')], max_length=50)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='lessons.module')),
            ],
            options={
                'verbose_name': 'Annanda',
                'verbose_name_plural': 'Annandat',
            },
        ),
    ]
