# Generated by Django 3.2.16 on 2025-02-03 23:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0014_auto_20250203_2325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="data",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
