# Generated by Django 3.2.16 on 2025-02-04 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_alter_exercise_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.module'),
        ),
    ]
