# Generated by Django 3.2.16 on 2025-02-05 01:51

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0016_alter_exercise_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
