# Generated by Django 3.2.16 on 2025-02-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0021_exercise_has_ansers_check"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="has_ansers_check",
            new_name="has_answers_check",
        ),
    ]
