# Generated by Django 3.2.16 on 2025-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0022_rename_has_ansers_check_exercise_has_answers_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("FillBlank", "Fill in the Blank Words"),
                    ("SyllableAssembly", "Syllable Assembly"),
                    ("FillBlankText", "Fill in the Blank Text"),
                    ("SentenceAssembly", "Sentence Assembly"),
                    ("MatchPair", "Match the Pair"),
                    ("FillBlankTable", "Fill in the Blank Table"),
                ],
                max_length=50,
            ),
        ),
    ]
