# Generated by Django 3.2.16 on 2025-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0028_alter_exercise_exercise_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("InteractiveHint", "Interactive Hints"),
                    ("FillBlank", "Fill in the Blank Words"),
                    ("SyllableAssembly", "Syllable Assembly"),
                    ("FillBlankText", "Fill in the Blank Text"),
                    ("SentenceAssembly", "Sentence Assembly"),
                    ("SentenceAssemblyPrefilled", "Sentence Assembly with Prefill"),
                    ("MatchPair", "Match the Pair"),
                    ("MatchPairMultiple", "Match the Pair (Multiple)"),
                    ("FillBlankTable", "Fill in the Blank Table"),
                    (
                        "MatchPairSentenceSlot",
                        "Match the Pair with slots for sentantions",
                    ),
                    ("FillGapWithChoice", "Fill Gap with Choice"),
                    ("FillWord", "Fillword Game"),
                ],
                max_length=50,
            ),
        ),
    ]
