# Generated by Django 3.2.16 on 2025-12-21 16:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0029_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['number'], 'verbose_name': 'Modulli', 'verbose_name_plural': 'Modullit'},
        ),
        migrations.CreateModel(
            name='GrammarComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='HTML content')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_comments', to='lessons.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Грамматический комментарий',
                'verbose_name_plural': 'Грамматические комментарии',
            },
        ),
        migrations.AddIndex(
            model_name='grammarcomment',
            index=models.Index(fields=['module'], name='lessons_gra_module__135c57_idx'),
        ),
    ]
