# Generated by Django 3.2.16 on 2025-12-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0030_auto_20251221_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grammarcomment",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grammar_comment",
                to="lessons.module",
                verbose_name="Модуль",
            ),
        ),
    ]
