# Generated by Django 3.2.16 on 2025-12-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0031_alter_grammarcomment_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcomment',
            name='lang',
            field=models.CharField(choices=[('ru', 'Hormiksi'), ('fi', 'Šuomekši')], default='ru', max_length=32),
        ),
    ]
