# Generated by Django 3.2.16 on 2025-12-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0032_grammarcomment_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcomment',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
