# Generated by Django 3.0.2 on 2020-01-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_auto_20200114_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.Pos'),
        ),
    ]
