# Generated by Django 3.0.2 on 2020-02-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0009_auto_20200207_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='definition',
            unique_together=set(),
        ),
    ]
