# Generated by Django 3.0.3 on 2020-08-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0018_auto_20200510_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarform',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='grammarform',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='wordform',
            name='form_id',
        ),
        migrations.AddField(
            model_name='grammarform',
            name='base',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grammarform',
            name='end',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='grammarform',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grammarform',
            name='pos',
            field=models.ManyToManyField(to='lexicon.Pos'),
        ),
        migrations.AddField(
            model_name='grammarform',
            name='pre',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='grammarform',
            name='rule',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='wordform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='lexicon.GrammarForm'),
        ),
    ]
