# Generated by Django 3.0.2 on 2020-01-15 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0004_auto_20200114_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_definition', to='lexicon.Word'),
        ),
    ]
