# Generated by Django 3.0.2 on 2020-02-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0008_auto_20200207_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="speech",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lexicon.Speech",
            ),
        ),
    ]
