# Generated by Django 3.0.3 on 2020-03-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0011_auto_20200213_2152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speech",
            name="text",
            field=models.TextField(db_index=True, null=True),
        ),
    ]
