# Generated by Django 3.0.3 on 2020-03-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0012_auto_20200315_0648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="alias",
            field=models.ManyToManyField(
                blank=True, related_name="_word_alias_+", to="lexicon.Word"
            ),
        ),
    ]
