# Generated by Django 3.0.3 on 2020-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0014_base_base_slug_diacrit"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="definition_lcase",
            field=models.TextField(blank=True),
        ),
    ]
