# Generated by Django 3.0.3 on 2020-05-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0015_definition_definition_lcase"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ru", models.CharField(max_length=128)),
                ("name_fi", models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name="base",
            old_name="base_slug_diacrit",
            new_name="base_slug_diacritic",
        ),
        migrations.CreateModel(
            name="WordForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base", models.CharField(max_length=128)),
                (
                    "base_slug",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "base_slug_diacritic",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "form_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_id",
                        to="lexicon.GrammarForm",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_set",
                        to="lexicon.Word",
                    ),
                ),
            ],
        ),
    ]
