# Generated by Django 3.0.3 on 2020-05-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0016_auto_20200509_1801"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wordform",
            old_name="base",
            new_name="form",
        ),
        migrations.RenameField(
            model_name="wordform",
            old_name="base_slug",
            new_name="form_slug",
        ),
        migrations.RenameField(
            model_name="wordform",
            old_name="base_slug_diacritic",
            new_name="form_slug_diacritic",
        ),
    ]
