# Generated by Django 3.0.3 on 2020-05-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0017_auto_20200509_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarform',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='grammarform',
            name='name_fi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='grammarform',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
