# Generated by Django 3.2.16 on 2024-12-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0021_word_word_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginat'},
        ),
    ]
