# Generated by Django 3.2.16 on 2025-12-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0022_alter_speech_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grammarform",
            name="pos",
        ),
        migrations.RemoveField(
            model_name="wordform",
            name="form",
        ),
        migrations.RemoveField(
            model_name="wordform",
            name="word",
        ),
        migrations.DeleteModel(
            name="Base",
        ),
        migrations.DeleteModel(
            name="GrammarForm",
        ),
        migrations.DeleteModel(
            name="WordForm",
        ),
    ]
