# Generated by Django 3.2.16 on 2025-12-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0023_auto_20251220_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem_type', models.CharField(choices=[('verb_0', 'Основа 0 (начальная форма - инфинитив)'), ('verb_1', 'Основа 1 (слабая презенс)'), ('verb_2', 'Основа 2 (сильная презенс)'), ('verb_3', 'Основа 3 (слабая имперфект)'), ('verb_4', 'Основа 4 (сильная имперфект)'), ('verb_5', 'Основа 5 (сильная/согласная)'), ('verb_6', 'Основа 6 (пассив слабая)'), ('verb_7', 'Основа 7 (пассив сильная)'), ('noun_0', 'Основа 0 (начальная форма - номинатив ед.ч.)'), ('noun_1', 'Основа 1 (слабая ед.ч.)'), ('noun_2', 'Основа 2 (сильная ед.ч.)'), ('noun_3', 'Основа 3 (партитив ед.ч.)'), ('noun_4', 'Основа 4 (слабая мн.ч.)'), ('noun_5', 'Основа 5 (сильная мн.ч.)'), ('adj_0', 'Основа 0 (начальная форма - номинатив ед.ч.)'), ('adj_1', 'Основа 1 (слабая ед.ч.)'), ('adj_2', 'Основа 2 (сильная ед.ч.)'), ('adj_3', 'Основа 3 (партитив ед.ч.)'), ('adj_4', 'Основа 4 (слабая мн.ч.)'), ('adj_5', 'Основа 5 (сильная мн.ч.)')], max_length=20)),
                ('number', models.PositiveSmallIntegerField()),
                ('form', models.CharField(max_length=256)),
                ('special_mark', models.CharField(blank=True, choices=[('', 'Нет пометы'), ('pl', 'Только мн.ч. (pl.)'), ('sing', 'Только ед.ч. (sing.)'), ('v_def', 'Только 3 л. (v. def.)')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stems', to='lexicon.word')),
            ],
            options={
                'verbose_name': 'Vardalo',
                'verbose_name_plural': 'Vardalot',
                'ordering': ['word', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='stem',
            index=models.Index(fields=['word', 'number'], name='lexicon_ste_word_id_b50c09_idx'),
        ),
        migrations.AddIndex(
            model_name='stem',
            index=models.Index(fields=['word'], name='lexicon_ste_word_id_43f916_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stem',
            unique_together={('word', 'stem_type')},
        ),
    ]
